<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>L1_Category1_HP</name>
   <tag></tag>
   <elementGuidId>25d0b878-f62e-4b2b-9231-b7b79e5acb52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='m-megamenu__category_menu-item'][1])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>28994e1b-97f3-407d-a441-a7f4ee4e88f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678033965677</value>
      <webElementGuid>664fa82e-5459-482f-bdd8-d1d1fcc79b92</webElementGuid>
   </webElementProperties>
</WebElementEntity>
