<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>L2CategoryInFlyout_HP</name>
   <tag></tag>
   <elementGuidId>59073cec-a5db-48fb-a859-c1bfa1e59e9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>((//div[@style=&quot;display: block;&quot;][1])//div[@class='a-scnd-catTitle'][1])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-desktop__categoryTitle.categoryLevel-2undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7d2c2a36-7ae4-460a-a646-f56dd98b66d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-desktop__categoryTitle categoryLevel-2undefined</value>
      <webElementGuid>b4dcb3d6-5d36-4edf-8417-e5f9c2f536dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ropa</value>
      <webElementGuid>7e128fb5-1368-4229-9e39-1b7e112ab363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CAT610036&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-top&quot;]/div[@class=&quot;col-lg-8 category-menu&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 pb-3&quot;]/a[@class=&quot;a-desktop__categoryTitle categoryLevel-2undefined&quot;]</value>
      <webElementGuid>b798a4aa-7c1e-4446-b67b-0634cb01decd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CAT610036']/div/div[2]/div/div/div/a</value>
      <webElementGuid>cd5b6ed0-7757-4f10-ace4-ec6c640cadda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ropa')]</value>
      <webElementGuid>54a69159-18c9-4be1-bf10-8b43fbf37206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ella'])[2]/following::a[1]</value>
      <webElementGuid>95df3de2-e695-4f49-b82f-16eba55a4af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ella'])[1]/following::a[2]</value>
      <webElementGuid>4e64a6a8-46e1-4b40-8df2-cc38322ce5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chamarras Abrigos &amp; Chalecos'])[1]/preceding::a[1]</value>
      <webElementGuid>3a3ff384-5a0b-471a-8f6a-c7b71e115da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suéteres &amp; Sudaderas'])[1]/preceding::a[2]</value>
      <webElementGuid>8c408143-0bc8-4b2d-8e15-1f024a97b3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ropa']/parent::*</value>
      <webElementGuid>c5b05c94-342f-4107-970d-d5313f92267c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>ba3c1e30-655f-4bba-8e3f-066f39d0cb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Ropa' or . = 'Ropa')]</value>
      <webElementGuid>69ca4b8f-2bf7-4c1d-b7e7-0d4ad2887b60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
