<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_product__image_misCompras</name>
   <tag></tag>
   <elementGuidId>7f7ba8ad-6dbc-4caf-bc96-8c921699ea0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-2.col-sm-3.col-md-3.col-lg-3.MisComprasProductImage > figure.MisCompImgWidth.MisCompProdImgWidth > img.a-order__product__image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='MisComprasProductImage'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>40881466-f51f-4b4f-bda8-84fc25019506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>6ff3ce42-267e-4419-b169-48c3b00fe7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss237.liverpool.com.mx/sm/1111964187.jpg</value>
      <webElementGuid>382f0cff-75d0-475f-95c8-109c4344849a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ZAPATO DOCKERS D2122, 28 CM, CHOCOLATE</value>
      <webElementGuid>d1e4f09b-20ec-4e08-b3b7-75fe69670932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-order__product__image</value>
      <webElementGuid>06fe56a8-4c05-49d0-a73e-7d2813861a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid o-main-container p-0&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/div[@class=&quot;col-lg-9 m-column_mainContent&quot;]/div[@class=&quot;MisComprasContainer d-none d-lg-block desktop&quot;]/div[3]/div[@class=&quot;col-xs-2 col-sm-3 col-md-3 col-lg-3 MisComprasProductImage&quot;]/figure[@class=&quot;MisCompImgWidth MisCompProdImgWidth&quot;]/img[@class=&quot;a-order__product__image&quot;]</value>
      <webElementGuid>624f7138-4235-490d-a1db-f4cf7942dece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[3]/div[2]/div[4]/div[3]/div/figure/img</value>
      <webElementGuid>6fa841be-b823-4d71-a549-6b2163ef1c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='ZAPATO DOCKERS D2122, 28 CM, CHOCOLATE'])[2]</value>
      <webElementGuid>4e7ab322-1592-4bed-b6c1-c7242d919df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/figure/img</value>
      <webElementGuid>decb9bb7-5a18-435b-8d04-dc5de21ffc42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss237.liverpool.com.mx/sm/1111964187.jpg' and @alt = 'ZAPATO DOCKERS D2122, 28 CM, CHOCOLATE']</value>
      <webElementGuid>43ffdb54-dab2-408c-a12b-90ab2f5c4d9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
