<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>L3_categoryMenu_HP</name>
   <tag></tag>
   <elementGuidId>f066bbc8-65e1-4ac4-a116-6c984f634d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>((//div[@class='m-megamenu__category_menu-item'])[1]//div[@class=&quot;a-thrd-catTitle&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
